### ISSUE TITLE
upsert-file: 500 Internal Server Error

### ISSUE THREAD

**Issue by dbigham** [openai/chatgpt-retrieval-plugin#159]
![image](https://user-images.githubusercontent.com/1895770/230700591-490309fa-4ee0-4c8d-b4d7-3c943d3618c4.png)

```
INFO:     Application startup complete.
mimetype: text/plain
file.file: <tempfile.SpooledTemporaryFile object at 0x00000256ABD06740>
file:  <starlette.datastructures.UploadFile object at 0x00000256ABD06CB0>
INFO:     127.0.0.1:51068 - "POST /upsert-file HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-GLI-4pa_-py3.10\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\danie\chatgpt-retrieval-plugin\server\main.py", line 63, in upsert_file
    document = await get_document_from_file(file, metadata_obj)
  File "C:\Users\danie\chatgpt-retrieval-plugin\services\file.py", line 17, in get_document_from_file
    extracted_text = await extract_text_from_form_file(file)
  File "C:\Users\danie\chatgpt-retrieval-plugin\services\file.py", line 103, in extract_text_from_form_file
    with open(temp_file_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/temp_file'
```

I'm on Windows, so it does seem suspect that it would be trying to write to `/tmp/`.

**Comment by dbigham** [comment]
Perhaps this is the same issue as: https://github.com/openai/chatgpt-retrieval-plugin/issues/153

**Comment by dbigham** [comment]
I've been able to work around this by using the `upsert` endpoint rather than the `upsert-file` endpoint.

**Comment by Jochen3000** [comment]
I got it to work with this change to file.py

Import
`import tempfile
import os`

Change extract_text_from_form_file:
`async def extract_text_from_form_file(file):
    # create a temporary directory to store the uploaded file
    temp_dir = tempfile.mkdtemp()
    temp_file_path = os.path.join(temp_dir, file.filename)
    mimetype = file.content_type
    print(f"mimetype: {mimetype}")
    print(f"file.file: {file.file}")
    print("file: ", file)   
    # write the file to a temporary location
    with open(temp_file_path, "wb") as f:
        f.write(await file.read())

    # extract the text from the file
    try:
        extracted_text = extract_text_from_filepath(temp_file_path, mimetype)
    except Exception as e:
        print(f"Error: {e}")
        os.remove(temp_file_path)
        raise e

    # remove file from temp location
    os.remove(temp_file_path)

    return extracted_text
`
