### ISSUE TITLE
ImportError: cannot import name 'BaseLanguageModel' when using locked version of LangChain

### ISSUE THREAD

**Issue by willg101** [openai/chatgpt-retrieval-plugin#250]
While following the quickstart, I encountered the following error when running `poetry run start`:

```
INFO:     Will watch for changes in these directories: ['/var/www']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [210] using WatchFiles
INFO:     Started server process [229]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/var/www/server/main.py", line 151, in startup
    datastore = await get_datastore()
  File "/var/www/datastore/factory.py", line 15, in get_datastore
    from datastore.providers.llama_datastore import LlamaDataStore
  File "/var/www/datastore/providers/llama_datastore.py", line 8, in <module>
    from llama_index.indices.base import BaseGPTIndex
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/keyword_table/base.py", line 17, in <module>
    from llama_index.indices.base import BaseGPTIndex, QueryMap
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/base.py", line 11, in <module>
    from llama_index.indices.query.base import BaseGPTIndexQuery
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 28, in <module>
    from llama_index.indices.response.builder import (
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/response/builder.py", line 18, in <module>
    from llama_index.indices.common_tree.base import GPTTreeIndexBuilder
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/common_tree/base.py", line 12, in <module>
    from llama_index.indices.service_context import ServiceContext
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 6, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/indices/prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/langchain_helpers/chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/llm_predictor/__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
  File "/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/llama_index/llm_predictor/base.py", line 12, in <module>
    from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (/root/.cache/pypoetry/virtualenvs/chatgpt-retrieval-plugin-p9HyaoIY-py3.10/lib/python3.10/site-packages/langchain/schema.py)

ERROR:    Application startup failed. Exiting.
```

I'm using the Dockerfile provided in this repo. 

Running `pip install langchain==0.0.153` seems to have fixed the issue for me, but I see this repo is locked to version 0.0.166.

In my testing, any version of LangChain >= 0.0.154 causes the error above when working within a container based on the provided Dockerfile.

**Comment by TsarPrince** [comment]
Same issue
